name: admin_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.0
  provider: ^6.0.1
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  shared_preferences: ^2.0.9
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.5
  flutter_animated_dialog: ^2.0.1
  firebase_storage: ^10.1.0
  cached_network_image: ^3.1.0+1
  pdf: ^3.6.3
  flutter_device_type: ^0.4.0
  image_picker: ^0.8.4+4
  downloads_path_provider_28: ^0.1.2
  syncfusion_flutter_pdf: ^19.3.57-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_wbg.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/font/kalpurush.ttf
    - assets/font/NotoSansBengali-Regular.ttf
  fonts:
    - family: kalpurush
      fonts:
        - asset: assets/font/kalpurush.ttf
    - family: NotoSans
      fonts:
        - asset: assets/font/NotoSansBengali-Regular.ttf